[versions]
compileSdk = "34"
lifecycleLivedataKtx = "2.8.6"
materialVersion = "1.12.0"
minSdk = "21"
pagingCompose = "3.3.2"
roomKtx = "2.6.1"
targetSdk = "33"
versionCode = "1"
versionName = "1.0.0"


accompanistFlowlayout = "0.30.0"
accompanistSystemuicontroller = "0.28.0"
android-core = "8.3.2"
androidxJunit = "1.1.1"
coilCompose = "2.2.0"
constraintlayoutCompose = "1.1.0-alpha13"
core = "1.2.0"
coreRuntime = "2.2.0"
coreTesting = "2.1.0"
espressoContrib = "3.2.0"
espressoIntents = "3.2.0"
exoplayer = "2.19.1"
firebase-crashlytics = "2.9.4"
google-hilt = "2.48.1"
google-maps-screts = "2.0.1"
google-services = "4.3.15"
google-ksp = "1.9.20-1.0.14"
junitVersion = "4.12"
kotlin-android = "1.9.20"
kotlin-jvm = "1.9.20"
androidx-activity = "1.8.1"
androidx-compose = "1.6.0-beta01"
androidx-compose-material-3 = "1.2.0-alpha11"
androidx-compose-bom = "2023.10.01"
androidx-core = "1.12.0"
androidx-datastore = "1.0.0"
androidx-hilt = "1.1.0"
androidx-lifecycle = "2.6.2"
androidx-livedata = "1.6.0-beta01"
androidx-viewmodel = "2.6.0-alpha05"
androidx-navigation = "2.7.5"
androidx-room = "2.6.0"
androidx-test-junit = "1.1.5"
androidx-test-espresso = "3.5.1"
androidx-work = "2.8.1"
firebase-bom = "32.6.0"
jetbrains-kotlin-reflect = "1.8.21"
jetbrains-kotlinx-coroutines = "1.7.1"
junit = "4.13.2"
google-accompanist = "0.31.1-alpha"
google-dagger = "2.48"
google-gson = "2.10.1"
google-maps = "2.9.1"
google-places = "3.3.0"
google-services-location = "21.0.1"
google-services-maps = "18.2.0"
lottie = "5.2.0"

mockitoAll = "1.10.19"
mockitoAndroid = "2.25.0"
mockitoCore = "2.25.0"
mockK = "1.13.5"
pdfbox = "2.0.27"
rules = "1.2.0"
runner = "1.2.0"
timber = "5.0.1"
okhttp3 = "4.11.0"
retrofit2 = "2.9.0"
uiTextGoogleFonts = "1.6.7"
webkit = "1.11.0"
material3Android = "1.3.0"
appcompat = "1.7.0"
material = "1.12.0"
pagingCommonAndroid = "3.3.2"
pagingComposeAndroid = "3.3.2"

[libraries]
# AndroidX Activity Compose
accompanist-flowlayout-v0300 = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanistFlowlayout" }
accompanist-systemuicontroller-v0280 = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx-compose" }
androidx-compose-ui-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose" }
androidx-compose-ui-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-compose" }
androidx-compose-ui-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx-compose" }

androidx-core-runtime = { module = "androidx.arch.core:core-runtime", version.ref = "coreRuntime" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoContrib" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt" }
androidx-junit-v111 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "androidx-livedata" }

androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }

androidx-room-ktx-vversion = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
core = { module = "androidx.test:core", version.ref = "core" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoIntents" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
google-accompanist-navigation-animation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "google-accompanist" }
google-accompanist-systemUiController = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "google-accompanist" }
google-accompanist-flowLayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "google-accompanist" }
google-accompanist-permission = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "google-accompanist" }
google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "google-dagger" }
google-dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "google-dagger" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "google-gson" }
google-maps = { group = "com.google.maps.android", name = "maps-compose", version.ref = "google-maps" }
google-places = { group = "com.google.android.libraries.places", name = "places", version.ref = "google-places" }
google-play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "google-services-location" }
google-play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "google-services-maps" }
junit-4 = { group = "junit", name = "junit", version.ref = "junit" }
junit-v412 = { module = "junit:junit", version.ref = "junitVersion" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "jetbrains-kotlin-reflect" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "jetbrains-kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "jetbrains-kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "jetbrains-kotlinx-coroutines" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mockito-all = { module = "org.mockito:mockito-all", version.ref = "mockitoAll" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockK" }
mockk-agent-jvm = { group = "io.mockk", name = "mockk-agent-jvm", version.ref = "mockK" }
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
rules = { module = "androidx.test:rules", version.ref = "rules" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-paging-common-android = { group = "androidx.paging", name = "paging-common-android", version.ref = "pagingCommonAndroid" }
androidx-paging-compose-android = { group = "androidx.paging", name = "paging-compose-android", version.ref = "pagingComposeAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-core" }
android-library = { id = "com.android.library", version.ref = "android-core" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
google-maps-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "google-maps-screts" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "google-hilt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
google-service = { id = "com.google.gms.google-services", version.ref = "google-services" }

[bundles]
androidx-compose = [
    "androidx-activity-compose",
    "androidx-compose-ui-ui",
    "androidx-compose-ui-ui-tooling-preview",
]
androidx-compose-debug = [
    "androidx-compose-ui-ui-tooling",
    "androidx-compose-ui-ui-test-manifest",
]
androidx-compose-integration-testing = [
    "androidx-compose-ui-ui-test-junit",
]
firebase = [
    "firebase-crashlytics",
]
google-accompanist = [
    "google-accompanist-flowLayout",
    "google-accompanist-navigation-animation",
    "google-accompanist-permission",
    "google-accompanist-systemUiController",
]
retrofit2 = [
    "retrofit2",
    "retrofit2-converter-gson",
]
